### ISSUE TITLE
Prepare for a 1.0 release

### ISSUE THREAD

**Issue by orta** [danger/swift#67]
Danger Swift works on a few projects in production now, so I think it's time to start thinking about what the 1.0 looks like. Happy to raise/lower the scope. 

## Supporting  all Danger JS features

- [x] GitHub / BitBucket work
- [x] Inline commenting
- [x] *Optional* support something like `danger pr` in JS  https://github.com/danger/danger-swift/issues/60
- [x] *Optional* support [something like](https://github.com/danger/danger-js/blob/master/CHANGELOG.md#310) `danger local` in JS

## Swift specifics

- [x] Make a Dangerfile edit mode
- [x] Consider whether running `danger-swift ci` can set up the node env and run everything for you
- [x] Find a way to allow custom GitHub API calls #17 
- [x] *Optional* Allow importing multiple files #49 
- [x] *Optional* Look at Linux support as a consumer #34 

## Docs

These should all live in this repo, and Danger.Systems can pull it all out at build time. This is what we do [with danger-js](https://github.com/danger/danger-js/tree/master/docs). I can handle all these.

- [x] API Reference (could be done via jazzy)
- [x] Installation Guide (I'd focus this on what the weird node dance is, and have a think about if that stuff can move into danger-swift also)
- [x] Getting Started Tutorial
- [x] Usage guides
- [x] Making a plugin https://github.com/danger/danger-swift/issues/46

**Comment by acecilia** [comment]
Related to:

> Optional support something like danger pr in JS #60

I am running Danger-swift in my local machine against a bitbucket server, and I plan to use it from Bamboo (which has no danger support) in the same way by using the following lines:

```
# Your repo URL is https://yourHost/pathToYourRepo

export DANGER_BITBUCKETSERVER_HOST='https://yourHost'
export DANGER_BITBUCKETSERVER_USERNAME='user'
export DANGER_BITBUCKETSERVER_PASSWORD='password'

# Fake CI. See: https://github.com/danger/danger-js/blob/master/docs/guides/the_dangerfile.html.md
export DANGER_FAKE_CI='YEP'
export DANGER_TEST_REPO='pathToYourRepo'
export DANGER_TEST_PR='PRNumber' #for example: export DANGER_TEST_PR='906'

danger process danger-swift
```

Isn't this providing the same functionality as `danger pr`?

**Comment by orta** [comment]
No, danger pr doesn’t write to checks or the pr, it’s a local dev tool

**Comment by orta** [comment]
OK, this is now *reallllllly* close. The only thing from my original list that I considered to be a blocker was support for making GitHub API calls from Danger Swift. 

Perhaps for Danger Swift, instead of providing a GitHub API ( #17 ) we make/use a simple API V4 query API?

Other than that it's time for documentation. So I need to find some sort of types to JSON thingy for the deploy process.

**Comment by orta** [comment]
Oh hey, so check it out all those boxes are ticked now - docs are shipped: https://danger.systems/swift/

and I've come up with a solution for plugins taking foreever, which I'll write up In #139 

so that leaves this pretty much good to 1.0 IMO

**Comment by f-meloni** [comment]
I suppose that, given 1.0.0 is released we can close this
